### ISSUE TITLE
MHE implementation

### ISSUE THREAD

**Issue by gmsanchez** [kul-forbes/nmpc-codegen#13]
Hi!
I wonder if there is a Moving Horizon Estimator (MHE) implementation using PANOC. If there is not an MHE impelmentation done, what would be the necessary steps to make one? 

Thanks in advance

**Comment by alphaville** [comment]
gmsanchez I would recommend that you use [OptimizationEngine](https://alphaville.github.io/optimization-engine/) - it is a project we developed after this one. You can find an example on [nonlinear estimation](https://alphaville.github.io/optimization-engine/docs/example_estimation_py) and moving horizon estimation [here](https://alphaville.github.io/optimization-engine/docs/example_estimation_py) (as well as [more examples](https://alphaville.github.io/optimization-engine/docs/python-examples)).

**Comment by gmsanchez** [comment]
@alphaville thanks for the quick response! I will check those links ASAP!
