### ISSUE TITLE
What's the meaning of tau?

### ISSUE THREAD

**Issue by KomicaReborn** [kul-forbes/nmpc-codegen#14]
Hello, I'm studying panoc recently. In your paper, the value of tau is Max {1 / 2 ^ i}. Isn't the value of tau 1? What's the meaning of this definition?

**Comment by MelisWillem** [comment]
@KomicaReborn first of all you should check out this panoc solver: https://github.com/Zilleplus/PANOCSharp . It's a much cleaner version that does exactly the same thing written in C#. It's a prototype for a new C++ version I am working on.

But to answer your question, tau is used to backtrack, we want to maximize the usuage of the accelerator. So if tau is 1 we use only the accelerator(lbfgs) if it's zero then this is a pure proximal gradient algorithm.

The FBE (forward backward envelop) is a special cost function that we use to backtrack. 

So we take the highest tau such that FBE(x_old) <FBE(x_new) 
-> with x_new = x_old + step_prox_grad*(tau-1) + step_lbfgs*tau.
you can find this [in the C# code](https://github.com/Zilleplus/PANOCSharp/blob/master/src/kul.forbes/Panoc.cs) at line 92 till 113

Or in the [C code](https://github.com/kul-forbes/nmpc-codegen/blob/master/PANOC/panoc.c) at line 120. But again I highly recommend to study the C# code first.

@alphaville , @lostella , @panpat  feel free to correct me here if I am wrong.

**Comment by lostella** [comment]
> So we take the highest tau such that FBE(x_old) <FBE(x_new)

The exact inequality you can find in eq (9) here: https://arxiv.org/pdf/1709.06487.pdf

Other than that, the above explanation is accurate

**Comment by KomicaReborn** [comment]
ok, thank you very much. My other question is where is the output interface of panoc solver?

**Comment by KomicaReborn** [comment]
> > So we take the highest tau such that FBE(x_old) <FBE(x_new)
> 
> The exact inequality you can find in eq (9) here: https://arxiv.org/pdf/1709.06487.pdf
> 
> Other than that, the above explanation is accurate

Thank you for your reply, I'm looking at your recommended paper. I will study it carefully (even if it is difficult)

**Comment by MelisWillem** [comment]
@KomicaReborn this repo is the share code used in nmpc-codegen-python and nmpc-codegen-matlab. You should use check out the demo's in those repo's.

**Comment by MelisWillem** [comment]
@KomicaReborn , @lostella  closing the issue
