### ISSUE TITLE
Matlab_test_utils error

### ISSUE THREAD

**Issue by eldemet** [kul-forbes/nmpc-codegen#3]
In Windows 10, MATLAB R2015a

```
>> Matlab_test_utils
Error: File: Matlab_test_utils.m Line: 46 Column: 1
Function definitions are not permitted in this context.
```

@alphaville, it seems that by moving the function to a different m-file (test_if_command_available.m), the script can be executed.

**Comment by alphaville** [comment]
@eldemet @Zilleplus That's right, thanks for reporting this. It seems that the problem is that there is a function definition inside a script.

**Comment by panpat** [comment]
I've also observed this. In the latest versions of MATLAB you are allowed to do that, but if someone is running an old version he gets and error. Willem, I suggest you remove functions from all scripts.

**Comment by Zilleplus** [comment]
I will double  check but that is one of the only places i used a "subfunction". The actual library is mostly classes so no problems there.
