### ISSUE TITLE
Trailer example not compiling (linker error)

### ISSUE THREAD

**Issue by korken89** [kul-forbes/nmpc-codegen#4]
Hi, I was trying the trailer matlab example, and when trying to run it I get a linker error as follows:

```
/home/emifre/Git/EmbeddedMPC/matlab/trailer.c: In function ‘trailer’:
/home/emifre/Git/EmbeddedMPC/matlab/trailer.c:8:10: warning: implicit declaration of function ‘casadi_f0’ [-Wimplicit-function-declaration]
   return casadi_f0(arg, res, iw, w, mem);
          ^

Error using mex
/tmp/mex_4258838998425_12530/trailer.o: In function `trailer':
trailer.c:(.text+0xa): undefined reference to `casadi_f0'
collect2: error: ld returned 1 exit status


Error in StaticWorldNavigator/mexifyPanoc (line 7)
mex('-I../include', '-L../dist/Release/GNU-Linux', ...

Error in StaticWorldNavigator/codegen (line 16)
obj.mexifyPanoc();

Error in testPANOCFramework (line 49)
ellFun                = nav.codegen(codegenOps)   ;
```

My system is as follows:
* Ubuntu 16.04
* Matlab 9.3.0.713579 (R2017b)
* Casadi casadi-linux-matlabR2014b-v3.4.4 (the 2014 and up version for linux)
* Tested on the master branch of `EmbeddedMPC`.

Tell me if there is something more you need.
Thanks!

BR Emil

**Comment by Zilleplus** [comment]
I assigned Pantelis to this issue as his more familiar with that library.  Casadi is not backward compatible, 
 at first glance at the error is suspect it has to do with the version. (i think you need 3.1 or 3.2)

Nmpc-codegen can do what EmbeddedMPC can and even more ! (same optimization algo ! but no paper on it) It supports the latest 3 versions of Casadi.

Check out: https://github.com/kul-forbes/nmpc-codegen/blob/master/demos/Matlab/demos.m 
It uses the same trailer model, just change the "name" variable to demo1,demo2,demo3 or demo4 and you get the same 4 simulations.

Please **read the very short install manual** of nmpc-codegen. (takes 1 minute)

**Comment by alphaville** [comment]
@Zilleplus I think in this project you used Casadi v3.2. I recently setup a new laptop and I downloaded casadi 3.1 and I just realized it gives errors. @korken89 can you check which version of casadi you use?

**Comment by Zilleplus** [comment]
@alphaville i never got embeddedMPC properly work, i simply hacked examples manually together. You use bash scripting inside you Makefiles, that's where things sometimes go wrong. (i think it was sid that errored) nmpc-codegen supports Casadi 3.2 or higher so 3.1 won't work indeed.

I actually detect the version i think it should error with "unsupported casadi version, exiting script" if you use the wrong one. You should do this too, this avoids leaving the user hanging with a weird error.

https://github.com/kul-forbes/nmpc-codegen/blob/master/src_matlab/%2Bnmpccodegen/%2Bcontroller/%40Casadi_code_generator/Casadi_code_generator.m

**Comment by korken89** [comment]
Hi, I tested with v3.2 then it did compile!
However the trailer example is still failing with the error:
```
Undefined function or variable 'indBox'.

Error in testPANOCFramework (line 80)
g = indBox(u_min, u_max);
```

Seems like some path is not correct.

**Comment by Zilleplus** [comment]
@korken89  i assume you did add the matlab and its sub folders to your path after you compiled the library?

**Comment by korken89** [comment]
Indeed I did.

**Comment by korken89** [comment]
Doing an ack-grep over the repository, there is no function defined as `indBox`.
The closest is:
```
matlab/helpers/indBox_circobs.m
29:function obj = indBox_circobs(lower, upper, circ, params)
31:    obj.makeprox = @() @(x, gam) call_indBoxcircobs_prox(x, lower, upper, circ, params);
36:function [prox, val] = call_indBoxcircobs_prox(x, lower, upper, circ, params) %modify to include more circles
```

**Comment by Zilleplus** [comment]
@alphaville you should take a look at this

@korken89 i highly recommend cloning this repo nmpc-codegen. It works with casadi 3.2  or higher .
just run https://github.com/kul-forbes/nmpc-codegen/blob/master/demos/Matlab/demos.m it contains the same  demos, just a bit faster. (the controller is completely implemented in C)

It makes use of Cmake/Make and Gcc, just make sure have these installed and in your path. The library does all the rest for you. No need to call any build file or anything, it is fully automated. Should take only a minute.

**Comment by korken89** [comment]
Cool, I will give more testing. I tried it a bit quick but got some errors that it did not find libstdc++, but it is installed.
I have to give it another look.

**Comment by Zilleplus** [comment]
@korken89 it's a known bug see:
https://kul-forbes.github.io/nmpc-codegen/install/Toolchain_install.html
Some Matlab installations on Linux have this, some haven't
