### ISSUE TITLE
Cmake not available

### ISSUE THREAD

**Issue by alphaville** [kul-forbes/nmpc-codegen#8]
On MATLAB 2017a, I run `Matlab_test_utils` and I get the following result:

```
This script will check if the nessesary tools are available
casadi version 3.2.3[OK]
GNU compiler [OK]
make [OK]
Error cmake is not available [NOT OK]
```
However, `cmake` is installed on my system (I have cmake version 2.8.12.2).

**Comment by Zilleplus** [comment]
does !cmake work?

**Comment by alphaville** [comment]
Yes, `!cmake` works - also `status = system('cmake')` works fine and returns status value `0`. Maybe the correct way to check whether `cmake` is installed is to test `system('cmake') == 0`.

**Comment by Zilleplus** [comment]
yes seems cleaner, we should change that.
